config/routes.rb
Rails.application.routes.draw do

  resources :clinics
  resources :colony_pop_events
  resources :colony_population_event_types
  resources :cat_events
  resources :trapping_projects
  get "begin_finalization/:id" => "trapping_projects#begin_finalization", as: "begin_finalization"
  get "continue_finalization/:id" => "trapping_projects#continue_finalization", as: "continue_finalization"
  post "complete_finalization/:id" => "trapping_projects#complete_finalization", as: "complete_finalization"

  resources :cat_event_outcomes
  resources :cat_event_types
  if ["colony-manager-demo-staging.herokuapp.com","colony-manager-demo.herokuapp.com"].include?(ENV["HOST_URL"]) || Rails.env == "development"
      root "colonies#index"
  else
      root "colonies#map"
  end

  devise_for :users, controllers: {
    passwords: 'users/passwords',
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    invitations: 'users/invitations'
  }
  match '/edit_invite_limit', to: 'users#edit_invite_limit', via: :all

  resources :deleted_cat_reasons
  resources :cats

  resources :saved_filters

  resources :categorizations

  resources :categories

  resources :status_codes

  resources :notes

  resources :role_values

  get 'add_user' => 'users#new'
  resources :users do 
    resources :notes
  end
  get "mass_assign" => "colonies#mass_assign"
  get "manage_duplicates" => "colonies#manage_duplicates"
  get "deleted_colonies" => "colonies#deleted_colonies"
  get "manage_colony_people/:id" => "colonies#manage_colony_people", as: "manage_colony_people"
  post "update_colony_person/colony/:id/person/:person_id/role/:role" => "colonies#update_colony_person", as: "update_colony_person"
  post "update_person_roles/person/:id/role_value_id/:role_value_id" => "people#update_person_roles", as: "update_person_roles"
  get "deleted_people" => "people#deleted_people"
  post "update_deleted_colonies" => "colonies#update_deleted_colonies"
  post "update_deleted_people" => "people#update_deleted_people"
  get "check_addresses" => "colonies#check_addresses"
  get "dashboard" => "colonies#dashboard"
  get "map" => "colonies#map"
  get "summary_report" => "colonies#summary_report"
  get "quick_create" => "cats#quick_create"
  get "deleted_cats" => "cats#deleted_cats"
  post "update_deleted_cats" => "cats#update_deleted_cats"
  get "colonies/autocomplete_colony_formatted_address"
  get "people/autocomplete_person_full_name"
  get "search_selection" => "colonies#search_selection"
  get "person_search_selection" => "people#search_selection"
  get "add_person" => "people#search"
  get "add_colony" => "colonies#search"

  resources :colonies do
    collection { post :import }
    resources :notes
    resources :cats do
      resources :notes
    end
  end

  resources :people

end

app/models/status_code.rb
class StatusCode < ActiveRecord::Base
	has_many :colonies
	has_many :colony_pop_events

	validates :status_code, uniqueness: true

	scope :not_deleted, -> { where('deleted is null') }
	scope :is_deleted, -> { where(:deleted => true) }
	scope :is_active, -> { where(:is_active => true) }
end

app/controllers/status_codes_controller.rb
class StatusCodesController < ApplicationController
  # Authentication with Devise. This line must be after the `protect_from_forgery` call (in application controller).
	before_action :authenticate_user!
  before_action :set_status_code, only: [:show, :edit, :update, :destroy]
  before_action :require_admin
  before_action :set_return_to, only: [:destroy]

  # GET /status_codes
  # GET /status_codes.json
  def index
    @status_codes = StatusCode.all
  end

  # GET /status_codes/1
  # GET /status_codes/1.json
  def show
  end

  # GET /status_codes/new
  def new
    @status_code = StatusCode.new
    @color_options = get_color_options(@status_code.color)
  end

  # GET /status_codes/1/edit
  def edit
    @color_options = get_color_options(@status_code.color)
  end

  # POST /status_codes
  # POST /status_codes.json
  def create
    @status_code = StatusCode.new(status_code_params)
    @status_code.created_by = current_user.id
    @status_code.color = params[:color]

    respond_to do |format|
      if @status_code.save
        format.html { redirect_to @status_code, notice: 'Status code was successfully created.' }
        format.json { render :show, status: :created, location: @status_code }
      else
        format.html { render :new }
        format.json { render json: @status_code.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /status_codes/1
  # PATCH/PUT /status_codes/1.json
  def update
    # fail
    @status_code.color = params[:color]
    respond_to do |format|
      if @status_code.update(status_code_params)
        format.html { redirect_to @status_code, notice: 'Status code was successfully updated.' }
        format.json { render :show, status: :ok, location: @status_code }
      else
        format.html { render :edit }
        format.json { render json: @status_code.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /status_codes/1
  # DELETE /status_codes/1.json
  def destroy
    if Colony.status_code_id(@status_code).size > 0
      respond_to do |format| 
        format.html { redirect_to session.delete(:return_to), alert: 'Status code can not be deleted while there are colonies assigned to it.' }
        format.json { head :no_content }
      end
    else
      @status_code.destroy
      respond_to do |format|
        format.html { redirect_to session.delete(:return_to), notice: 'Status code was successfully destroyed.' }
        format.json { head :no_content }
      end
    end
  end

  private

    def get_color_options(selected_color)
      colors = { "Green" => "#7bd148" , 
                  "Bold blue" => "#5484ed" , 
                  "Blue" => "#a4bdfc" , 
                  "Turquoise" => "#46d6db" , 
                  "Light green" => "#7ae7bf" , 
                  "Bold green" => "#51b749" , 
                  "Yellow" => "#fbd75b" , 
                  "Orange" => "#ffb878" , 
                  "Red" => "#ff887c" , 
                  "Bold red" => "#dc2127" , 
                  "Purple" => "#dbadff" , 
                  "Gray" => "#e1e1e1",
                  "Olive" => "#808000",
                  "Maroon" => "#800000",
                  "Dark blue" => "#00008B",
                  "Blue gray" => "#98AFC7"
                }

      color_options = ""
      colors.each do |name,hex|
        selected = " selected" if selected_color == hex
        color_options += "<option value='#{hex}'#{selected}>#{name}</option>"
      end
      color_options
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_status_code
      @status_code = StatusCode.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def status_code_params
      params.require(:status_code).permit(:status_code, :description, :is_active, :created_by, :deleted_by, :deleted_at, :color)
    end
end

app/helpers/status_codes_helper.rb
module StatusCodesHelper
end

app/views/status_codes/_form.html.erb
<%= form_for(@status_code) do |f| %>
  <% if @status_code.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@status_code.errors.count, "error") %> prohibited this status_code from being saved:</h2>

      <ul>
      <% @status_code.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :status_code %><br>
    <%= f.text_field :status_code, autofocus: true, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :description %><br>
    <%= f.text_field :description, class: 'form-control' %>
  </div>
  <div class="form-group">
    <label>Choose Color</label>
    <select id="status_code_color" name="color" class="form-control">
      <%= @color_options.html_safe %>
    </select>
  </div>
  <div class="form-group">
    <%= f.label :is_active %><br>
    <%= f.check_box :is_active %>
  </div>
  <div class="form-group">
    <%= f.submit 'Submit', :class => 'btn btn-primary' %>
  </div>
<% end %>

app/views/status_codes/edit.html.erb
<div class='row'>
  <div class='col-md-3'>
  </div>
  <div class='col-md-6'>
    <div class='panel panel-primary'>
      <div class='panel panel-heading'>
        <h4>Edit Status Code</h4>
      </div>
      <div class='panel panel-body'>

		<%= render 'form' %>

		<%= link_to 'Show', @status_code, class: 'btn btn-primary' %>
		<%= link_to 'Cancel', status_codes_path, class: 'btn btn-default' %>
      </div>
    </div>
  </div>
  <div class='col-md-3'>
  </div>
</div>

app/views/status_codes/index.html.erb
<div class='row'>
  <div class="col-md-3">
  </div>
  <div class='col-md-6'>
    <div class='panel panel-primary'>
      <div class="panel-heading"><h4>Manage Status Codes</h4></div>
        <div class="panel-body">
          <div class='col-md-12'>
            <table class='table table-striped'>
              <thead>
                <tr>
                  <th>Status code</th>
                  <th>Description</th>
                  <th>Color</th>
                  <th>Is active</th>
                  <th>Created by</th>
                  <th>Actions</th>
                </tr>
              </thead>

              <tbody>
                <% @status_codes && @status_codes.each do |status_code| %>
                  <tr>
                    <% created_by_user = user(status_code.created_by) %>
                    <td><%= status_code.status_code %></td>
                    <td><%= status_code.description %></td>
                    <td><span class='label label-default' style="background-color:<%= status_code.color %>;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span></td>
                    <td><%= status_code.is_active %></td>
                    <td><%= created_by_user.nil? ? "deleted user" : created_by_user.name %></td>
                    <td><%= link_to 'Show', status_code %> | <%= link_to 'Edit', edit_status_code_path(status_code) %> | <%= link_to 'Destroy', status_code, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                  </tr>
                <% end %>
              </tbody>
            </table>
            <%= link_to 'New Status code', new_status_code_path, class: 'btn btn-primary' %>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="col-md-3">
  </div>    
</div>

app/views/status_codes/new.html.erb
<div class='row'>
  <div class='col-md-3'>
  </div>
  <div class='col-md-6'>
    <div class='panel panel-primary'>
      <div class='panel panel-heading'>
        <h4>Add Status Code</h4>
      </div>
      <div class='panel panel-body'>
		<%= render 'form' %>

		<%= link_to 'Cancel', status_codes_path, class: 'btn btn-default' %>
      </div>
    </div>
  </div>
  <div class='col-md-3'>
  </div>
</div>

app/views/status_codes/show.html.erb
<div class='row'>
  <div class='col-md-3'>
  </div>
  <div class='col-md-6'>
    <div class='panel panel-primary'>
      <div class='panel panel-heading'>
        <h4>Display Status Code</h4>
      </div>
      <div class='panel panel-body'>
        <p>
          <strong>Status code:</strong>
          <%= @status_code.status_code %>
        </p>
        <p>
          <strong>Description:</strong>
          <%= @status_code.description %>
        </p>
        <p>
          <strong>Color:</strong>
          <span class='label label-default' style="background-color:<%= @status_code.color %>;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span>
        </p>
        <p>
          <strong>Is active:</strong>
          <%= @status_code.is_active %>
        </p>

        <p>
          <strong>Created by:</strong>
          <%= user(@status_code.created_by).name %>
        </p>

        <p>
          <strong>Deleted by:</strong>
          <%= @status_code.deleted_by %>
        </p>

        <p>
          <strong>Deleted at:</strong>
          <%= @status_code.deleted_at %>
        </p>

        <%= link_to 'Edit', edit_status_code_path(@status_code), class: 'btn btn-primary' %> 
        <%= link_to 'Cancel', status_codes_path, class: 'btn btn-default' %>
        <%= link_to 'New Status code', new_status_code_path, class: 'btn btn-primary' %>
      </div>
    </div>
  </div>
  <div class='col-md-3'>
  </div>
</div>