config/routes.rb
Rails.application.routes.draw do

  resources :clinics
  resources :colony_pop_events
  resources :colony_population_event_types
  resources :cat_events
  resources :trapping_projects
  get "begin_finalization/:id" => "trapping_projects#begin_finalization", as: "begin_finalization"
  get "continue_finalization/:id" => "trapping_projects#continue_finalization", as: "continue_finalization"
  post "complete_finalization/:id" => "trapping_projects#complete_finalization", as: "complete_finalization"

  resources :cat_event_outcomes
  resources :cat_event_types
  if ["colony-manager-demo-staging.herokuapp.com","colony-manager-demo.herokuapp.com"].include?(ENV["HOST_URL"]) || Rails.env == "development"
      root "colonies#index"
  else
      root "colonies#map"
  end

  devise_for :users, controllers: {
    passwords: 'users/passwords',
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    invitations: 'users/invitations'
  }
  match '/edit_invite_limit', to: 'users#edit_invite_limit', via: :all

  resources :deleted_cat_reasons
  resources :cats

  resources :saved_filters

  resources :categorizations

  resources :categories

  resources :status_codes

  resources :notes

  resources :role_values

  get 'add_user' => 'users#new'
  resources :users do 
    resources :notes
  end
  get "mass_assign" => "colonies#mass_assign"
  get "manage_duplicates" => "colonies#manage_duplicates"
  get "deleted_colonies" => "colonies#deleted_colonies"
  get "manage_colony_people/:id" => "colonies#manage_colony_people", as: "manage_colony_people"
  post "update_colony_person/colony/:id/person/:person_id/role/:role" => "colonies#update_colony_person", as: "update_colony_person"
  post "update_person_roles/person/:id/role_value_id/:role_value_id" => "people#update_person_roles", as: "update_person_roles"
  get "deleted_people" => "people#deleted_people"
  post "update_deleted_colonies" => "colonies#update_deleted_colonies"
  post "update_deleted_people" => "people#update_deleted_people"
  get "check_addresses" => "colonies#check_addresses"
  get "dashboard" => "colonies#dashboard"
  get "map" => "colonies#map"
  get "summary_report" => "colonies#summary_report"
  get "quick_create" => "cats#quick_create"
  get "deleted_cats" => "cats#deleted_cats"
  post "update_deleted_cats" => "cats#update_deleted_cats"
  get "colonies/autocomplete_colony_formatted_address"
  get "people/autocomplete_person_full_name"
  get "search_selection" => "colonies#search_selection"
  get "person_search_selection" => "people#search_selection"
  get "add_person" => "people#search"
  get "add_colony" => "colonies#search"

  resources :colonies do
    collection { post :import }
    resources :notes
    resources :cats do
      resources :notes
    end
  end

  resources :people

end

app/controllers/cat_event_types_controller.rb
class CatEventTypesController < ApplicationController
  before_action :set_cat_event_type, only: %i[ show edit update destroy ]
  before_action :authenticate_user!
  before_action :require_admin

  # GET /cat_event_types or /cat_event_types.json
  def index
    @cat_event_types = CatEventType.all
  end

  # GET /cat_event_types/1 or /cat_event_types/1.json
  def show
  end

  # GET /cat_event_types/new
  def new
    @cat_event_type = CatEventType.new
  end

  # GET /cat_event_types/1/edit
  def edit
  end

  # POST /cat_event_types or /cat_event_types.json
  def create
    @cat_event_type = CatEventType.new(cat_event_type_params)
    @cat_event_type.created_by = current_user.id

    respond_to do |format|
      if @cat_event_type.save
        format.html { redirect_to @cat_event_type, notice: "Cat event type was successfully created." }
        format.json { render :show, status: :created, location: @cat_event_type }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @cat_event_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cat_event_types/1 or /cat_event_types/1.json
  def update
    respond_to do |format|
      if @cat_event_type.update(cat_event_type_params)
        format.html { redirect_to @cat_event_type, notice: "Cat event type was successfully updated." }
        format.json { render :show, status: :ok, location: @cat_event_type }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @cat_event_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cat_event_types/1 or /cat_event_types/1.json
  def destroy
    @cat_event_type.destroy
    respond_to do |format|
      format.html { redirect_to cat_event_types_url, notice: "Cat event type was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cat_event_type
      @cat_event_type = CatEventType.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def cat_event_type_params
      params.require(:cat_event_type).permit(:type_name, :type_description, :is_active, :deleted_at, :is_deleted, :created_by, :deleted_by, :is_system_type)
    end
end

app/helpers/cat_event_types_helper.rb
module CatEventTypesHelper
end

app/views/cat_event_types/_form.html.erb
<%= form_with(model: cat_event_type) do |form| %>
  <% if @cat_event_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cat_event_type.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @cat_event_type.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <% if @cat_event_type.is_system_type %>
    <div class="alert alert-info role="alert">
      This Cat Event Type is a system-required type, and may not be modified or disabled.
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :type_name %>
    <%= form.text_field :type_name, autofocus: true, class: 'form-control', disabled: @cat_event_type.is_system_type %>
  </div>

  <div class="form-group">
    <%= form.label :type_description %>
    <%= form.text_field :type_description, class: 'form-control', disabled: @cat_event_type.is_system_type %>
  </div>

  <div class="form-group">
    <%= form.label :is_active %>
    <%= form.check_box :is_active, disabled: @cat_event_type.is_system_type %>
  </div>

  <div class="form-group">
    <%= form.submit :class => 'btn btn-primary' %>
  </div>
<% end %>

app/views/cat_event_types/edit.html.erb
<div class='row'>
  <div class='col-md-3'>
  </div>
  <div class='col-md-6'>
    <div class='panel panel-primary'>
      <div class='panel panel-heading'>
        <h4>Edit Cat Event Type</h4>
      </div>
      <div class='panel panel-body'>

        <%= render 'form', cat_event_type: @cat_event_type %>

        <%= link_to 'Show', @cat_event_type, class: 'btn btn-primary' %>
		<%= link_to 'Back', cat_event_types_path, class: 'btn btn-default' %>
      </div>
    </div>
  </div>
  <div class='col-md-3'>
  </div>
</div>

app/views/cat_event_types/index.html.erb
<div class='row'>
  <div class="col-md-2">
  </div>
  <div class='col-md-8'>
    <div class='panel panel-primary'>
      <div class="panel-heading"><h4>Manage Cat Event Types</h4></div>
        <div class="panel-body">
          <div class='col-md-12'>

            <table id='data_table' class='display'>
              <thead>
                <tr>
                  <th>Type name</th>
                  <th>Type description</th>
                  <th>Is active</th>
                  <th>Created by</th>
                  <th>Is system type</th>
                  <th>Actions</th>
                </tr>
              </thead>

              <tbody>
                <% @cat_event_types.each do |cat_event_type| %>
                  <tr>
                    <td><%= cat_event_type.type_name %></td>
                    <td><%= cat_event_type.type_description %></td>
                    <td><%= cat_event_type.is_active %></td>
                    <td><%= user(cat_event_type.created_by) && user(cat_event_type.created_by).name %></td>
                    <td><%= cat_event_type.is_system_type ? cat_event_type.is_system_type : "false" %></td>
                    <td><%= link_to 'Show', cat_event_type %> <%= link_to 'Edit', edit_cat_event_type_path(cat_event_type) %></td>
                  </tr>
                <% end %>
              </tbody>
            </table>

          <%= link_to 'New Cat Event Type', new_cat_event_type_path, class: 'btn btn-primary' %>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="col-md-2">
  </div>    
</div>

app/views/cat_event_types/new.html.erb
<div class='row'>
  <div class='col-md-3'>
  </div>
  <div class='col-md-6'>
    <div class='panel panel-primary'>
      <div class='panel panel-heading'>
        <h4>New Cat Event Type</h4>
      </div>
      <div class='panel panel-body'>

        <%= render 'form', cat_event_type: @cat_event_type %>

		<%= link_to 'Back', cat_event_types_path, class: 'btn btn-default' %>
      </div>
    </div>
  </div>
  <div class='col-md-3'>
  </div>
</div>

app/views/cat_event_types/show.html.erb
<div class='row'>
  <div class='col-md-3'>
  </div>
  <div class='col-md-6'>
    <div class='panel panel-primary'>
      <div class='panel panel-heading'>
        <h4>Display Cat Event Type</h4>
      </div>
      <div class='panel panel-body'>
        <p>
          <strong>Type name:</strong>
          <%= @cat_event_type.type_name %>
        </p>

        <p>
          <strong>Description:</strong>
          <%= @cat_event_type.type_description %>
        </p>

        <p>
          <strong>Is active:</strong>
          <%= @cat_event_type.is_active %>
        </p>

        <p>
          <strong>Created by:</strong>
          <%= user(@cat_event_type.created_by) && user(@cat_event_type.created_by).name %>
        </p>

        <p>
          <strong>Is system type:</strong>
          <%= @cat_event_type.is_system_type ? @cat_event_type.is_system_type : "false" %>
        </p>


        <%= link_to 'Edit', edit_cat_event_type_path(@cat_event_type), class: 'btn btn-primary' %>
        <%= link_to 'Cancel', cat_event_types_path, class: 'btn btn-default' %> 
        <% if current_user.admin %>
          <%= link_to( 'New Cat Event Type', new_cat_event_type_path, class: 'btn btn-primary') %>
        <% end %>

      </div>
    </div>
  </div>
  <div class='col-md-3'>
  </div>
</div>