config/routes.rb
Rails.application.routes.draw do

  resources :clinics
  resources :colony_pop_events
  resources :colony_population_event_types
  resources :cat_events
  resources :trapping_projects
  get "begin_finalization/:id" => "trapping_projects#begin_finalization", as: "begin_finalization"
  get "continue_finalization/:id" => "trapping_projects#continue_finalization", as: "continue_finalization"
  post "complete_finalization/:id" => "trapping_projects#complete_finalization", as: "complete_finalization"

  resources :cat_event_outcomes
  resources :cat_event_types
  if ["colony-manager-demo-staging.herokuapp.com","colony-manager-demo.herokuapp.com"].include?(ENV["HOST_URL"]) || Rails.env == "development"
      root "colonies#index"
  else
      root "colonies#map"
  end

  devise_for :users, controllers: {
    passwords: 'users/passwords',
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    invitations: 'users/invitations'
  }
  match '/edit_invite_limit', to: 'users#edit_invite_limit', via: :all

  resources :deleted_cat_reasons
  resources :cats

  resources :saved_filters

  resources :categorizations

  resources :categories

  resources :status_codes

  resources :notes

  resources :role_values

  get 'add_user' => 'users#new'
  resources :users do 
    resources :notes
  end
  get "mass_assign" => "colonies#mass_assign"
  get "manage_duplicates" => "colonies#manage_duplicates"
  get "deleted_colonies" => "colonies#deleted_colonies"
  get "manage_colony_people/:id" => "colonies#manage_colony_people", as: "manage_colony_people"
  post "update_colony_person/colony/:id/person/:person_id/role/:role" => "colonies#update_colony_person", as: "update_colony_person"
  post "update_person_roles/person/:id/role_value_id/:role_value_id" => "people#update_person_roles", as: "update_person_roles"
  get "deleted_people" => "people#deleted_people"
  post "update_deleted_colonies" => "colonies#update_deleted_colonies"
  post "update_deleted_people" => "people#update_deleted_people"
  get "check_addresses" => "colonies#check_addresses"
  get "dashboard" => "colonies#dashboard"
  get "map" => "colonies#map"
  get "summary_report" => "colonies#summary_report"
  get "quick_create" => "cats#quick_create"
  get "deleted_cats" => "cats#deleted_cats"
  post "update_deleted_cats" => "cats#update_deleted_cats"
  get "colonies/autocomplete_colony_formatted_address"
  get "people/autocomplete_person_full_name"
  get "search_selection" => "colonies#search_selection"
  get "person_search_selection" => "people#search_selection"
  get "add_person" => "people#search"
  get "add_colony" => "colonies#search"

  resources :colonies do
    collection { post :import }
    resources :notes
    resources :cats do
      resources :notes
    end
  end

  resources :people

end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :categorizations, dependent: :destroy
	has_many :colonies, through: :categorizations
	has_many :people, through: :categorizations

	scope :for_colonies, -> { where model: "Colony" }
	scope :for_people, -> { where model: "Person" }
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  # Authentication with Devise. This line must be after the `protect_from_forgery` call (in application controller).
	before_action :authenticate_user!
  before_action :set_category, only: [:show, :edit, :update, :destroy]
  before_action :require_admin, only: [:destroy]
  before_action :set_return_to, only: [:destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to session.delete(:return_to), notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name, :description, :deleted, :deleted_by, :deleted_at, :model)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %><br>
    <%= f.text_field :name, autofocus: true, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :description %><br>
    <%= f.text_field :description, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :applies_to %>
    <%= f.select :model, options_for_select(['Select','Colony','Person'], @category.model), {}, {class: 'form-control'} %>
    <% if action_name == 'edit' %>
      <span id="helpBlock" class="text-danger">NOTE: If you change this value, the association of this category with existing <%= @category.model %> records will be removed.</span>
    <% end %>
  </div>
  <div class="form-group">
    <%= f.submit :class => 'btn btn-primary' %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<div class='row'>
  <div class='col-md-3'>
  </div>
  <div class='col-md-6'>
    <div class='panel panel-primary'>
      <div class='panel panel-heading'>
        <h4>Edit Category</h4>
      </div>
      <div class='panel panel-body'>

		<%= render 'form' %>

		<%= link_to 'Show', @category, class: 'btn btn-primary' %>
		<%= link_to 'Cancel', categories_path, class: 'btn btn-default' %>
      </div>
    </div>
  </div>
  <div class='col-md-3'>
  </div>
</div>

app/views/categories/index.html.erb
<div class='row'>
  <div class="col-md-2">
  </div>
  <div class='col-md-8'>
    <div class='panel panel-primary'>
      <div class="panel-heading"><h4>Manage Categories</h4></div>
        <div class="panel-body">
          <div class='col-md-12'>

            <table id='data_table' class='display'>
              <thead>
                <tr>
                  <th>Name</th>
                  <th>Description</th>
                  <th>Applies to</th>
                  <th>Actions</th>
                </tr>
              </thead>

              <tbody>
                <% @categories.each do |category| %>
                  <tr>
                    <td><%= category.name %></td>
                    <td><%= category.description %></td>
                    <td><%= category.model %></td>
                    <td><%= link_to 'Show', category %> | <%= link_to 'Edit', edit_category_path(category) %> | <%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                  </tr>
                <% end %>
              </tbody>
            </table>

          <%= link_to 'New Category', new_category_path, class: 'btn btn-primary' %>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="col-md-2">
  </div>    
</div>

app/views/categories/new.html.erb
<div class='row'>
  <div class='col-md-3'>
  </div>
  <div class='col-md-6'>
    <div class='panel panel-primary'>
      <div class='panel panel-heading'>
        <h4>New Category</h4>
      </div>
      <div class='panel panel-body'>

		<%= render 'form' %>

		<%= link_to 'Cancel', categories_path, class: 'btn btn-default' %>
      </div>
    </div>
  </div>
  <div class='col-md-3'>
  </div>
</div>

app/views/categories/show.html.erb
<div class='row'>
  <div class='col-md-3'>
  </div>
  <div class='col-md-6'>
    <div class='panel panel-primary'>
      <div class='panel panel-heading'>
        <h4>Display Categories</h4>
      </div>
      <div class='panel panel-body'>
        <p>
          <strong>Name:</strong>
          <%= @category.name %>
        </p>

        <p>
          <strong>Description:</strong>
          <%= @category.description %>
        </p>

        <p>
          <strong>Applies to:</strong>
          <%= @category.model %>
        </p>


        <%= link_to 'Edit', edit_category_path(@category), class: 'btn btn-primary' %>
        <%= link_to 'Cancel', categories_path, class: 'btn btn-default' %> 
        <% if current_user.admin %>
        <%= link_to( 'New Category', new_category_path, class: 'btn btn-primary') %>
        <% end %>

      </div>
    </div>
  </div>
  <div class='col-md-3'>
  </div>
</div>