config/routes.rb
Rails.application.routes.draw do

  resources :clinics
  resources :colony_pop_events
  resources :colony_population_event_types
  resources :cat_events
  resources :trapping_projects
  get "begin_finalization/:id" => "trapping_projects#begin_finalization", as: "begin_finalization"
  get "continue_finalization/:id" => "trapping_projects#continue_finalization", as: "continue_finalization"
  post "complete_finalization/:id" => "trapping_projects#complete_finalization", as: "complete_finalization"

  resources :cat_event_outcomes
  resources :cat_event_types
  if ["colony-manager-demo-staging.herokuapp.com","colony-manager-demo.herokuapp.com"].include?(ENV["HOST_URL"]) || Rails.env == "development"
      root "colonies#index"
  else
      root "colonies#map"
  end

  devise_for :users, controllers: {
    passwords: 'users/passwords',
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    invitations: 'users/invitations'
  }
  match '/edit_invite_limit', to: 'users#edit_invite_limit', via: :all

  resources :deleted_cat_reasons
  resources :cats

  resources :saved_filters

  resources :categorizations

  resources :categories

  resources :status_codes

  resources :notes

  resources :role_values

  get 'add_user' => 'users#new'
  resources :users do 
    resources :notes
  end
  get "mass_assign" => "colonies#mass_assign"
  get "manage_duplicates" => "colonies#manage_duplicates"
  get "deleted_colonies" => "colonies#deleted_colonies"
  get "manage_colony_people/:id" => "colonies#manage_colony_people", as: "manage_colony_people"
  post "update_colony_person/colony/:id/person/:person_id/role/:role" => "colonies#update_colony_person", as: "update_colony_person"
  post "update_person_roles/person/:id/role_value_id/:role_value_id" => "people#update_person_roles", as: "update_person_roles"
  get "deleted_people" => "people#deleted_people"
  post "update_deleted_colonies" => "colonies#update_deleted_colonies"
  post "update_deleted_people" => "people#update_deleted_people"
  get "check_addresses" => "colonies#check_addresses"
  get "dashboard" => "colonies#dashboard"
  get "map" => "colonies#map"
  get "summary_report" => "colonies#summary_report"
  get "quick_create" => "cats#quick_create"
  get "deleted_cats" => "cats#deleted_cats"
  post "update_deleted_cats" => "cats#update_deleted_cats"
  get "colonies/autocomplete_colony_formatted_address"
  get "people/autocomplete_person_full_name"
  get "search_selection" => "colonies#search_selection"
  get "person_search_selection" => "people#search_selection"
  get "add_person" => "people#search"
  get "add_colony" => "colonies#search"

  resources :colonies do
    collection { post :import }
    resources :notes
    resources :cats do
      resources :notes
    end
  end

  resources :people

end

app/models/cat_event_outcome.rb
class CatEventOutcome < ApplicationRecord
    has_many :cat_events
end

app/controllers/cat_event_outcomes_controller.rb
class CatEventOutcomesController < ApplicationController
  before_action :set_cat_event_outcome, only: %i[ show edit update destroy ]
  before_action :authenticate_user!
  before_action :require_admin

  # GET /cat_event_outcomes or /cat_event_outcomes.json
  def index
    @cat_event_outcomes = CatEventOutcome.all
  end

  # GET /cat_event_outcomes/1 or /cat_event_outcomes/1.json
  def show
  end

  # GET /cat_event_outcomes/new
  def new
    @cat_event_outcome = CatEventOutcome.new
  end

  # GET /cat_event_outcomes/1/edit
  def edit
  end

  # POST /cat_event_outcomes or /cat_event_outcomes.json
  def create
    @cat_event_outcome = CatEventOutcome.new(cat_event_outcome_params)
    @cat_event_outcome.created_by = current_user.id

    respond_to do |format|
      if @cat_event_outcome.save
        format.html { redirect_to @cat_event_outcome, notice: "Cat event outcome was successfully created." }
        format.json { render :show, status: :created, location: @cat_event_outcome }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @cat_event_outcome.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cat_event_outcomes/1 or /cat_event_outcomes/1.json
  def update
    respond_to do |format|
      if @cat_event_outcome.update(cat_event_outcome_params)
        format.html { redirect_to @cat_event_outcome, notice: "Cat event outcome was successfully updated." }
        format.json { render :show, status: :ok, location: @cat_event_outcome }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @cat_event_outcome.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cat_event_outcomes/1 or /cat_event_outcomes/1.json
  def destroy
    @cat_event_outcome.destroy
    respond_to do |format|
      format.html { redirect_to cat_event_outcomes_url, notice: "Cat event outcome was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cat_event_outcome
      @cat_event_outcome = CatEventOutcome.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def cat_event_outcome_params
      params.require(:cat_event_outcome).permit(:name, :description, :is_active, :deleted_at, :is_deleted, :created_by, :deleted_by, :is_system_outcome, :remove_cat)
    end
end

app/helpers/cat_event_outcomes_helper.rb
module CatEventOutcomesHelper
end

app/views/cat_event_outcomes/_form.html.erb
<%= form_with(model: cat_event_outcome) do |form| %>
  <% if @cat_event_outcome.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cat_event_outcome.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @cat_event_outcome.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <% if @cat_event_outcome.is_system_outcome %>
    <div class="alert alert-info role="alert">
      This Cat Event Outcome is a system-required outcome, and may not be modified or disabled.
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, autofocus: true, class: 'form-control', disabled: @cat_event_outcome.is_system_outcome %>
  </div>

  <div class="form-group">
    <%= form.label :description %>
    <%= form.text_field :description, class: 'form-control', disabled: @cat_event_outcome.is_system_outcome %>
  </div>

  <div class="form-group">
    <%= form.label :is_active %>
    <%= form.check_box :is_active, disabled: @cat_event_outcome.is_system_outcome %>
  </div>

  <div class="form-group">
    <%= form.label :remove_cat %>
    <%= form.check_box :remove_cat, disabled: @cat_event_outcome.is_system_outcome %>
  </div>

  <div class="form-group">
    <%= form.submit :class => 'btn btn-primary' %>
  </div>
<% end %>

app/views/cat_event_outcomes/edit.html.erb
<div class='row'>
  <div class='col-md-3'>
  </div>
  <div class='col-md-6'>
    <div class='panel panel-primary'>
      <div class='panel panel-heading'>
        <h4>Edit Cat Event Outcome</h4>
      </div>
      <div class='panel panel-body'>

        <%= render 'form', cat_event_outcome: @cat_event_outcome %>

        <%= link_to 'Show', @cat_event_outcome, class: 'btn btn-primary' %>
		<%= link_to 'Back', cat_event_outcomes_path, class: 'btn btn-default' %>
      </div>
    </div>
  </div>
  <div class='col-md-3'>
  </div>
</div>

app/views/cat_event_outcomes/index.html.erb
<div class='row'>
  <div class="col-md-2">
  </div>
  <div class='col-md-8'>
    <div class='panel panel-primary'>
      <div class="panel-heading"><h4>Manage Cat Event Outcomes</h4></div>
        <div class="panel-body">
          <div class='col-md-12'>

            <table id='data_table' class='display'>
              <thead>
                <tr>
                  <th>Name</th>
                  <th>Description</th>
                  <th>Is active</th>
                  <th>Created by</th>
                  <th>Is system outcome</th>
                  <th>Remove Cat?</th>
                  <th>Actions</th>
                </tr>
              </thead>

              <tbody>
                <% @cat_event_outcomes.each do |cat_event_outcome| %>
                  <tr>
                    <td><%= cat_event_outcome.name %></td>
                    <td><%= cat_event_outcome.description %></td>
                    <td><%= cat_event_outcome.is_active %></td>
                    <td><%= user(cat_event_outcome.created_by) && user(cat_event_outcome.created_by).name %></td>
                    <td><%= cat_event_outcome.is_system_outcome ? cat_event_outcome.is_system_outcome : "false" %></td>
                    <td><%= cat_event_outcome.remove_cat ? cat_event_outcome.remove_cat : "false" %></td>
                    <td><%= link_to 'Show', cat_event_outcome %> <%= link_to 'Edit', edit_cat_event_outcome_path(cat_event_outcome) %> </td>
                  </tr>
                <% end %>
              </tbody>
            </table>

          <%= link_to 'New Cat Event Outcome', new_cat_event_outcome_path, class: 'btn btn-primary' %>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="col-md-2">
  </div>    
</div>

app/views/cat_event_outcomes/new.html.erb
<div class='row'>
  <div class='col-md-3'>
  </div>
  <div class='col-md-6'>
    <div class='panel panel-primary'>
      <div class='panel panel-heading'>
        <h4>New Cat Event Outcome</h4>
      </div>
      <div class='panel panel-body'>

        <%= render 'form', cat_event_outcome: @cat_event_outcome %>

		<%= link_to 'Back', cat_event_outcomes_path, class: 'btn btn-default' %>
      </div>
    </div>
  </div>
  <div class='col-md-3'>
  </div>
</div>

app/views/cat_event_outcomes/show.html.erb
<div class='row'>
  <div class='col-md-3'>
  </div>
  <div class='col-md-6'>
    <div class='panel panel-primary'>
      <div class='panel panel-heading'>
        <h4>Display Cat Event Outcome</h4>
      </div>
      <div class='panel panel-body'>
      <p>
        <strong>Name:</strong>
        <%= @cat_event_outcome.name %>
      </p>
      
      <p>
        <strong>Description:</strong>
        <%= @cat_event_outcome.description %>
      </p>
      
      <p>
        <strong>Is active:</strong>
        <%= @cat_event_outcome.is_active %>
      </p>
      
      <p>
        <strong>Remove cat?:</strong>
        <%= @cat_event_outcome.remove_cat ? "true" : "false" %>
      </p>

      <p>
        <strong>Created by:</strong>
        <%= user(@cat_event_outcome.created_by) && user(@cat_event_outcome.created_by).name %>
      </p>
      
      <p>
        <strong>Is system outcome:</strong>
        <%= @cat_event_outcome.is_system_outcome ? @cat_event_outcome.is_system_outcome : "false" %>
      </p>


        <%= link_to 'Edit', edit_cat_event_outcome_path(@cat_event_outcome), class: 'btn btn-primary' %>
        <%= link_to 'Cancel', cat_event_outcomes_path, class: 'btn btn-default' %> 
        <% if current_user.admin %>
          <%= link_to( 'New Cat Event Outcome', new_cat_event_outcome_path, class: 'btn btn-primary') %>
        <% end %>

      </div>
    </div>
  </div>
  <div class='col-md-3'>
  </div>
</div>